name: Rpn Calculator 2022

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test with unittest
        run: |
          python3 -m unittest discover -p "*_test.py"
      - name: Lint with Pylint
        run: |
          python3 -m pylint rpn-calculator

